### ISSUE TITLE
Server crash after start

### ISSUE THREAD

**Issue by IceNet** [Ovahlord/TrinityCore#13]
**Description:**

I can't start the battlenet/worldserver. Compiled it without any errors

**Current behaviour:**

After i start the battlenet/worldserver, i get the message "(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted."

Crashlog:
https://gist.github.com/IceNet/7a282fb8540d708a7474bd3ac680ec32

**Steps to reproduce the problem:**

1. I don't know how to reproduce it..

**Branch(es):**

4.3.4

**TC rev. hash/commit:** 

ba85a5ec9fb0+ 2019-10-09 13:59:25 +0200 (4.3.4 branch)

**Operating system:** 
Windows Server 2016

**Comment by CrossUCI** [comment]
Are you sure that you compile the lastest core, because there is not longer authserver , now is a bnetserver, like draenor core or legion core, and then you have to patch the client with a connection_patcher , but i do all of that and still getting issue with the client, i dont know that it work with set realmlist or set portal, i try both but when i try to loggin the client freeze and then give an error and after exit the client appears a Wow Error window and i create the account like this .bnetaccount create cross@uci.cu pass

**Comment by IceNet** [comment]
Yes, my fault, sry
I mean Battlenet/Worldserver

**Comment by Ovahlord** [comment]
@CrossUCI you need to make sure that you patch clean original client binary files. You cannot just repatch a already patched file.

@IceNet what is your system setup exactly? What versions of the software requirements do you use?

**Comment by CrossUCI** [comment]
@Ovahlord but still have my question it is with set portal in config.wtf, or it is with set realmlist in realmlist.wtf

**Comment by Ovahlord** [comment]
realmlist is no longer a thing. its deprecated

**Comment by Ovahlord** [comment]
No response from the ticket author so case closed.

**Comment by IceNet** [comment]
Sorry for late reply
System setup:
Boost: 1.66
Cmake: 3.12.4
MySQL: 5.6.45
OpenSSL: 1.0.2t
VS: 2017
GIT: 2.23

**Comment by funjoker** [comment]
According to login. Please check your client connection log and give it us.

**Comment by CrossUCI** [comment]
I find something rare, i delete config.wtf on WTF folder in order to the client generate this file by himself but when i open it appears this , another thing is that my compile core is before the submit of this commit  #12 and @Ovahlord  answer me in a old post that realmlist is deprecated but still have my question it is with set portal  " "  on config.wtf file , so we have to put there manually ?
SET 127.0.0.1:8081 " "

**Comment by Ovahlord** [comment]
Dude.
SET portal "127.0.0.1"

make sure you have all auth modules installed from the patching process and that's it. Seriously.

**Comment by CrossUCI** [comment]
Bro if i ask is because i can not login, if you see the WowError 2d try to login.txt you will find that i already used SET portal "127.0.0.1" in config.wtf

**Comment by IceNet** [comment]
Ok, i figured out how it works
You can download the patched files fpr 127.0.0.1 here:

https://files.it-library.eu/?dl=308155194030a95f97f9c104d15c3ed2

But the next problem is, when i'm in the realm select screen, i can't join the realm (seems like a blocked port, but on localhost possible?)

**Comment by CrossUCI** [comment]
i download the file, i uncompressed it and replace the existing files, when i try it to login it said connecting but after a little while client crash again, i suppose that i will have to recompile the new core and keep trying

**Comment by funjoker** [comment]
Patches Battle.net.dll must be named "Battle.net.dll"
Config must be correct `SET portal "ServerHere"`

GIVE ME CONNECTIONLOG!!!!!

**Comment by CrossUCI** [comment]
This is my connection log 

10/14 15:02:59.285  Login program=WoW platform=Win locale=esES
10/14 15:02:59.369  Component WoW.Win.15595
10/14 15:02:59.413  Component WoW.base.15595
10/14 15:02:59.447  Component WoW.enGB.15595
10/14 15:02:59.479  Component WoW.esES.15595
10/14 15:02:59.505  Component Tool.Win.0
10/14 15:03:00.860  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
10/14 15:03:01.159  Connecting to 127.0.0.1:1119
10/14 15:03:20.620  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
10/14 15:03:20.638  Disconnected from 127.0.0.1
10/14 15:03:20.651  Client initiated Disconnect from 127.0.0.1
10/14 15:03:20.679  Client initiated Disconnect from 127.0.0.1
10/14 15:03:20.703  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
10/14 15:03:20.722  Login program=WoW platform=Win locale=esES
10/14 15:03:20.745  Component WoW.Win.15595
10/14 15:03:20.771  Component WoW.base.15595
10/14 15:03:20.793  Component WoW.enGB.15595
10/14 15:03:20.827  Component WoW.esES.15595
10/14 15:03:20.849  Component Tool.Win.0

**Comment by funjoker** [comment]
Seems like you are missing correct .auth files in Blizzard Cache at ProgramData

**Comment by CrossUCI** [comment]
@funjoker what i suppose to do , when my client crash say this
Patch data download failed.
Error downloading patch data from server 'http://streaming.corp.blizzard.net/patchlist/ldap.php' , error code : nameResolveError

**Comment by funjoker** [comment]
This does not matter.

**Comment by CrossUCI** [comment]
Well i guess i will never can test again this server

**Comment by funjoker** [comment]
If you did correctly, the client would not crash. :/

**Comment by CrossUCI** [comment]
Of course bro , i even recompile the core from the last release yesterday, this is the only that can explain that the patch doesn’t work when i used the connection_patcher in the console say that everything is ok.

Creating patched binary...
Win32 client...
Patching client binary...
patching redirect RSA Modulus
Found offset 7961504
Patching done.
Patching battle.net binary...
patching Portal
Found offset 1694224
patching Bnet
Found offset 864857
patching Signature
Found offset 134009
Patching done.
Patching module...

But after the patching i go to crashes folder from client then appear this
[unknown_connection_patcher.exe_[15-10_10-42-49].txt](https://github.com/Ovahlord/TrinityCore/files/3729940/unknown_connection_patcher.exe_.15-10_10-42-49.txt)
