### ISSUE TITLE
[Spell] Paladin Templar's Verdict

### ISSUE THREAD

**Issue by Phantoms123** [Ovahlord/TrinityCore#2]
Paladin spell Templar's Verdict sometimes is a little buggy it seems, sometimes it hits and doesnt use up the holy power or divine purpose proc. Needs to be checked and tested by others first

The issue with divine purpose is that it was eating/using the proc but proccing off of it again, not sure if its meant to do this though.

using the holy power it seems to be working just fine now, maybe i was wrong about it.

neverless need others to test too

**Comment by Ovahlord** [comment]
Soo, any news about this issue here?

**Comment by Phantoms123** [comment]
Well like I said, just test out the spell and see if anything I mentioned is happening.

I don't think that divine purpose should be proccing off of itself though, so probably need to check that because it happens sometimes to me and the holy power thing needs to be checked just incase too

**Comment by Ovahlord** [comment]
My tests have been showing that Holy Power is getting consumed as it should and until now I have not been lucky enough to proc Divine Purpose twice in a row to see if it procs from itself.

**Comment by Phantoms123** [comment]
all is working well, can mark as fixed :)

**Comment by Ovahlord** [comment]
Nice to hear :)
