### ISSUE TITLE
[Core] Itemlevel calculation bug with Dungeon/Raid Finder

### ISSUE THREAD

**Issue by chovie23q** [Ovahlord/TrinityCore#3]
Itemlevel calculation bug with Dungeon/Raid Finder.

Basically it all seems to be working fine but for some reason it can bug out depending on situation, for example take a look at the screen shots below:

Seems to be working just fine here

https://imgur.com/a/EdDyGGj

But now take a look, I removed my weapon lowering it but now look at the dungeon finder

https://imgur.com/a/8CwMyH1

Dont know why this happens but shouldnt be doing that anyway, should be the same all around, thats a current problem on official TrinityCore atm too, but it seems work better here due to a possible custom fix

PS,
This all happens in both Dungeon finder & Raid finder

**Comment by Ovahlord** [comment]
I think I know what is happening. When you unequip your two handed weapon, the core also checks your offhand weapon slot which seems to should not happen when both slots are empty. Will investigate soon(tm)

**Comment by Ovahlord** [comment]
Fixed in  f8fa10949147295def79767545c3628bd7864606
