### ISSUE TITLE
Core: Could not load MMAP

### ISSUE THREAD

**Issue by GMKyle** [Ovahlord/TrinityCore#31]
Hash/commit: b96f544f94e1374d221f7cd2f7991d9611452c91
OS: Debian 9
My server console keep showing this 2 lines every few minutes:
Could not load MMAP name:Kalimdor, id:1, x:17, y:30 (mmap rep.: x:17, y:30)
Could not load MMAP name:Eastern Kingdoms, id:0, x:36, y:32 (mmap rep.: x:36, y:32)

And when worldserver its loading:
Could not load MMAP name:Eastern Kingdoms, id:0, x:48, y:26 (mmap rep.: x:48, y:26)

**Comment by Ovahlord** [comment]
This is not a bug. This is merely a message that pops up when a transport is in a grid cell that has no mmaps like when it's on a ocean.
