### ISSUE TITLE
Quest: Hero's Call: Darkshore! (28490) - Pristess Dentaria is missing?

### ISSUE THREAD

**Issue by funar** [Ovahlord/TrinityCore#34]
TrinityCore rev. 8acc08fcbad1 2019-02-25 08:25:59 +0100 (4.3.4 branch) (Unix, RelWithDebInfo, Static)

The quest, "Hero's Call: Darkshore! (28490)" cannot be completed as Priestess Dentaria seems to be missing. She's usually in Lor'danel standing in front of the tent where the flight master is or sitting on the bed upstairs in the inn.

**Comment by Ovahlord** [comment]
invalid ticket. She is spawned but has a quest invisbility aura which needs quest support
