### ISSUE TITLE
[Paladin Set Bonus T13]

### ISSUE THREAD

**Issue by Crypticaz** [Ovahlord/TrinityCore#4]
One of the set bonuses for paladin T13 set isn't working properly. It says 'Your judgement ability now also generates 1 Holy Power' when using judgement no holy power is received.

**Comment by Phantoms123** [comment]
Confirmed

**Comment by Phantoms123** [comment]
Spell set bonus ID : 105765

Needs some check possibly in the script for Judgement spell, something like

if(oncast)
If(check for aura = 2P bonus = 105765)
generate 1 holy power

something like that

**Comment by Crypticaz** [comment]
I'm thinking spell_linked_spell for this fix? Not sure how to go about fixing set bonuses

**Comment by Ovahlord** [comment]
No, this would be a hack. By looking at the aura of the set bonus this merely needs a spell_proc entry

**Comment by Ovahlord** [comment]
fixed in 64796f1121feff9e92e3013f5db3ede4feb84fac
