### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MariaCata** [Ovahlord/TrinityCore#4]
Hi tnx for hard work on this core!
I have a question.

Can you show me this function in trinity new

`bool Unit::HandleDummyAuraProc(Unit* victim, uint32 damage, AuraEffect* triggeredByAura, SpellInfo const* procSpell, uint32 procFlag, uint32 procEx, uint32 cooldown)`

**Comment by Ovahlord** [comment]
It's gone and it will never return. Procs are suposed to be handled via aurascripts with their proc hooks. everything else is a hack and should not get used at all
