### ISSUE TITLE
Arena Battlemaster & Organizer

### ISSUE THREAD

**Issue by Kitzunu** [Ovahlord/TrinityCore#42]
**Description:**

Used to queue for arena and set up arena team
I searched around on the Github but found now working fix

**Current behaviour:**

Arena Battlemaster got no Arena gossip
Arena Organizer got no Arena Team create window (Nothing happens when you right click the npc either)

**Expected behaviour:**

You should be able to queue arenas with the Arena Battlemaster
You should be able to create an Arena team with the Arena Organizer

**Steps to reproduce the problem:**

Try to interact with the Arena Organizer & Battlemaster

**Comment by Ovahlord** [comment]
have fun leeching it.
