### ISSUE TITLE
[Scripts][Core] Strange errors(Visual Bug?)

### ISSUE THREAD

**Issue by Phantoms123** [Ovahlord/TrinityCore#5]
Strange errors with the Beauty boss fix possibly just something visual.

In visual studio I get some errors with instance_blackrock_caverns.cpp at line 72, 77 & 81.

boss_beauty.cpp does the same but at 69 - 236.

https://imgur.com/a/3HXWYHP

They all seem to be class/member fucntion errors or pointer errors, but yet it builds no problem but shows them as errors when I have the files open.

I have the latest version which I just pulled like 5 mins ago

**Comment by Phantoms123** [comment]
I'm just using the default settings and following trinitycores install guide and making sure I got tools ticked and mysql setup with the right linking/directory

**Comment by Phantoms123** [comment]
it all compiles just fine though so im not sure

**Comment by Phantoms123** [comment]
Boss seems to be working ok ingame, no crashes, cast spells etc

**Comment by Ovahlord** [comment]
I did not cover loot yet. Will follow after scripting is done.

**Comment by Ovahlord** [comment]
Well, I don't see any error like this so probably your Intellisense just got messed up. Also this is not a real issue if it has no effect.
