### ISSUE TITLE
Crash: Exit Game

### ISSUE THREAD

**Issue by gbmv33** [Ovahlord/TrinityCore#50]
Have a bug when you try to exit from the game, my char try to summon something and the worldserver.exe crash instantly

unit.cpp:3378 in Unit::_AddAura ASSERTION FAILED:
  !m_cleanupDone

**Comment by Ovahlord** [comment]
more details please and try to fix your english so I can actually understand what you mean

**Comment by gbmv33** [comment]
If you let the character get AFK for a while and click exit game with the instant logout, the character tries to summon the mount because of auto mount and the server crash after that.

sorry for my english. ( google translator )

**Comment by gbmv33** [comment]
if you want I can give you the crash log

**Comment by gbmv33** [comment]
and another Crash:

Assertion message: 
d:\trinitybuilder\source\tc-cata\src\server\game\entities\creature\creature.cpp:1540 in Creature::LoadFromDB ASSERTION FAILED:
  m_respawnCompatibilityMode || sPoolMgr->IsPartOfAPool<Creature>(spawnId)
Creature (SpawnID 44457) trying to load despite a respawn timer in progress.
Fault address:  00007FF6076014BF 01:00000000007304BF C:\Users\servidor\Desktop\SPP_Classics_Collection\SPP_Classics_Collection\Server\Binaries\cata\Bin64\worldserver.exe

I can not say the cause of this one because I do not know

**Comment by Ovahlord** [comment]
compile in debug mode, not in release mode please. the crashlog that you get when you compile in release mode does not contain useful information to work with

**Comment by gbmv33** [comment]
ok
