### ISSUE TITLE
Quest: Save Krennan Aranas (14293) - Crashing server

### ISSUE THREAD

**Issue by gbmv33** [Ovahlord/TrinityCore#55]
when the horse arrives at the end of the quest the server crash

**Comment by Ovahlord** [comment]
please add a debug crashlog...

**Comment by gbmv33** [comment]
how i found it?

**Comment by gbmv33** [comment]
this are spammed in worldserver.exe console:

AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 83470 proc, because the spell does not have an entry in Spell.dbc.

[5389375babba_worldserver.exe_[28-3_21-30-17].txt](https://github.com/Ovahlord/TrinityCore/files/3020626/5389375babba_worldserver.exe_.28-3_21-30-17.txt)
