### ISSUE TITLE
Crash: Creature (SpawnID 44457)

### ISSUE THREAD

**Issue by gbmv33** [Ovahlord/TrinityCore#57]
Exception code: C0000420 Declaration failure
[cf9825dd82c5_worldserver.exe_[30-3_17-40-1].txt](https://github.com/Ovahlord/TrinityCore/files/3025971/cf9825dd82c5_worldserver.exe_.30-3_17-40-1.txt)
.

Assertion message: 
c:\users\servidor\desktop\trinitycata\trinitybuilder\source\trinitycore_legacy\src\server\game\entities\creature\creature.cpp:1540 in Creature::LoadFromDB ASSERTION FAILED:
  m_respawnCompatibilityMode || sPoolMgr->IsPartOfAPool<Creature>(spawnId)
Creature (SpawnID 44457) trying to load despite a respawn timer in progress.
Fault address:  00007FF75CEE4EEF 01:00000000013D3EEF C:\Users\servidor\Desktop\trinitycata\TrinityBuilder\Build\TrinityCore_Legacy_Win64\bin\Debug\worldserver.exe

**Comment by Ovahlord** [comment]
duplicate issue: https://github.com/Ovahlord/TrinityCore/issues/26
