### ISSUE TITLE
Pet System

### ISSUE THREAD

**Issue by IustinGanea** [Ovahlord/TrinityCore#8]
I'm using the last revision with all updates made corectly and whenever I make a new hunter or any other character which summons a pet, it seems that the pet doesn't have the skills action bar.
This happens for shaman, warlock, hunter etc.

**Comment by Ovahlord** [comment]
This is not a issue. You need to learn Control Pet / Control Demon to be able to command your pet in any way. That's blizzlike and correct.

**Comment by IustinGanea** [comment]
My bad, I've researched this and you are right. Thanks for info.
